name: Dumping fw

 

on:

  push:

    paths-ignore:

      - '*.md'

    branches: [ main ]

defaults:

  run:

    shell: bash

env:

  ROM_URL: https://bigota.d.miui.com/V13.0.14.0.RKCMIXM/miui_VEUXGlobal_V13.0.14.0.RKCMIXM_cb9ffa7184_11.0.zip

  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

       - name: Checkouts

         uses: actions/checkout@v2

       - name: Clone Dumpyara

         run: |

              sudo apt install neofetch -y

              git clone https://github.com/fw-dumps/DumprX dumper



       - name: Setup Dumpyara environment

         working-directory: dumper

         run: |

              sudo bash setup.sh

              git config --global user.name "Nouboi"

              git config --global user.email "atharvnegi1106@gmail.com"

       - name: Setup config envs

         working-directory: dumper

         run: |

              echo "${{ secrets.GIT_TOKEN }}" > .github_token

              echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname

              echo "${{ secrets.BOT_TOKEN }}" > .tg_token

              echo "${{ secrets.CHAT_ID }}" > .tg_chat

       - name: Running Dumpyara

         working-directory: dumper

         run: |

              ./dumper.sh $ROM_URL
